color0 #091614
color1 #ffb4ab
color2 #a0d57a
color3 #acd28f
color4 #82d5c9
color5 #a0d57a
color6 #acd28f
color7 #d7e6e2
color8 #7c9691
color9 #ffb4ab
color10 #a0d57a
color11 #acd28f
color12 #82d5c9
color13 #a0d57a
color14 #acd28f
color15 #d7e6e2

cursor                #d7e6e2
cursor_text_color     #091614
background            #091614
foreground            #d7e6e2
selection_foreground  #b1ccc7
selection_background  #324b47
active_border_color   #a0d57a
inactive_border_color #324b47
url_color             #a0d57a

active_tab_foreground   #163800
active_tab_background   #a0d57a
inactive_tab_foreground #b1ccc7
inactive_tab_background #324b47
cursor_trail_color      #b1ccc7
